# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6df77024ec0180c1f7bc31f37dea5faec5f5d4a5de8068489f1bb846962a48385ea90a24934c9dcff31ce9ee784c080d4b7e1132100dbeafebea1e576691594

test:
  secret_key_base: fe7f73a1f7114bbef3a2613ff6225b33f3ebbfd8893081e368a99395c8c5528ed54e0307f3c336694d0a8f27759b87559a830fa0c353fef6fad2abd1fffb8adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
